---
language: python

python:
  - "3.7"

services:
  - docker

env:
  global:
    - namespace="robertdebock/"
  matrix:
    - image="docker-alpine-openrc"
    - image="docker-alpine-openrc" tag="edge"
    # - namespace="archlinux/" image="base"
    - image="docker-centos-systemd" tag="7"
    - image="docker-centos-systemd"
    - image="docker-debian-systemd" tag="stable"
    - image="docker-debian-systemd" tag="unstable"
    - image="docker-debian-systemd"
    - image="docker-fedora-systemd"
    - image="docker-fedora-systemd" tag="rawhide"
    - namespace="opensuse/" image="leap"
    - image="docker-ubuntu-systemd" tag="rolling"
    - image="docker-ubuntu-systemd" tag="devel"
    - image="docker-ubuntu-systemd"

matrix:
  allow_failures:
    - env: image="docker-alpine-openrc" tag="edge"
    - env: image="docker-debian-systemd" tag="unstable"
    - env: image="docker-fedora-systemd" tag="rawhide"
    - env: image="docker-ubuntu-systemd" tag="rolling"
    - env: image="docker-ubuntu-systemd" tag="devel"

cache:
  - pip

install:
  - pip install --upgrade pip
  - pip install tox

script:
  - tox --parallel all

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    secure: "F5lqv+ao54xp2qL8XFCxzkXrszhfQLJN92AUFnoeg2nNdYdnGJd8s/RSJ0Dg0iYc+WJsV5wHxZmitrqYig46RNjWbHKVhsBkXUifmcTkmSEP5KVumq30yeJp55uU00Wa8xQQp42P3PasjYrCmEPlWFS4DoYiyIwGt49MuGTp4slzfn7xYdCc3THRKUDXePexccLaBFrMW9K2XIcku3reaV/Xf41I51CQgT5Chvz11+iSqGOQ888cWpqc+uRKj3I1SN/Yb16gXuWxzyL7w9kicuR3EG5zLXQBqLXrcnZp3ydRn6mfGn9A1siS1YlUuWBXizxCRAOp6B0slDQy5G9MITT0lvUqjjmFzdIPChRYNBsqHF0MsuHA3Ocf4myZ2QUW+nAzIv7wMZ/RrI1uL41FFa9qMFSlE3zcTJlWwHakmV31+aFFvPO4AykyAQt1Ofb/p3OeaP8lW6RS3DYFGHXpArDcn/mmS22IMnz/nh5zEdEIXdYRB6ql3u3IujCQp9PZkcdbFN7ZEQaCIrKNaV53+1Ku84c0gkGKqR8DkAPQfQtd3PotNzJUtlD3P9bzPocatZAb5BdqKO3ZcggrG7OVZ9CofrjoCdB73/DKGDG0mRPElmWYHFiORAUCzitan4/XE65yORVbogI58TWHcGEN2S6j1tCtE1FG65rd7bYgX5E="
  email: false
